document.addEventListener('DOMContentLoaded', () => {
    const modeAuto = document.getElementById('mode-auto');
    const modeManual = document.getElementById('mode-manual');
    const manualOptions = document.getElementById('manual-options');
    const scheduleSection = document.getElementById('schedule-section');
    const setScheduleBtn = document.getElementById('set-schedule');
    const stopScheduleBtn = document.getElementById('stop-schedule');
    const scheduleResult = document.getElementById('schedule-result');
    const aiOutput = document.getElementById('ai-output');

    modeAuto.addEventListener('change', () => {
        if (modeAuto.checked) {
            manualOptions.classList.add('d-none');
            scheduleSection.classList.add('d-none');
            aiOutput.classList.remove('d-none');
            aiOutput.textContent = 'Output generated by AI.';
        }
    });

    modeManual.addEventListener('change', () => {
        if (modeManual.checked) {
            manualOptions.classList.remove('d-none');
            aiOutput.classList.add('d-none');
        }
    });

    document.getElementById('water-on').addEventListener('change', () => {
        scheduleSection.classList.remove('d-none');
    });

    document.getElementById('water-off').addEventListener('change', () => {
        scheduleSection.classList.add('d-none');
        scheduleResult.textContent = '';
    });

    setScheduleBtn.addEventListener('click', () => {
        const scheduleTime = document.getElementById('schedule-time').value;
        if (scheduleTime) {
            scheduleResult.textContent = `Water supply scheduled at ${scheduleTime}.`;
            setScheduleBtn.classList.add('d-none');
            stopScheduleBtn.classList.remove('d-none');
        }
    });

    stopScheduleBtn.addEventListener('click', () => {
        scheduleResult.textContent = 'Water supply scheduling stopped.';
        stopScheduleBtn.classList.add('d-none');
        setScheduleBtn.classList.remove('d-none');
    });
});